### ISSUE TITLE
Add a preview mode

### ISSUE THREAD

**Issue by toolmantim** [buildkite/terminal#18]
Add some kind of ability to see the rendered output with stylesheet and all.

It could be as simple as a `--layout` flag which outputs the HTML container and CSS as well as the terminal output, so you can do:

```bash
mycommand | terminal --preview > /tmp/preview.html && open /tmp/preview.html
```

**Comment by mipearson** [comment]
Fixed by https://github.com/buildkite/terminal/pull/23
