### ISSUE TITLE
Allow to print links

### ISSUE THREAD

**Issue by byroot** [buildkite/terminal#29]
SInce we can include images, I suppose links should not be too difficult.

Proposed syntax: 
```bash
printf '\033]1337;url='"$1"';content='"$2"'\a\n'
```

The use case would be to enrich test failure backtraces so that each line is a link to the file on GitHub.

**Comment by toolmantim** [comment]
This is a great idea… we should absolutely support this! Stay tuned.

**Comment by mipearson** [comment]
I have a working prototype for this, but it's highlighted that I really need to clean up the image handling code.

Format is `1339;url=http://www.google.com;content=Google Search`

**Comment by mipearson** [comment]
https://github.com/buildkite/terminal/pull/30

@toolmantim @keithpitt does this syntax work for you?

**Comment by keithpitt** [comment]
Looks legit to me! Nothing is jumping out at me as being wrong with it.

**Comment by toolmantim** [comment]
Nice!! :+1: on the syntax

**Comment by toolmantim** [comment]
Shipped in #30
