### ISSUE TITLE
Allow to colorize links

### ISSUE THREAD

**Issue by byroot** [buildkite/terminal#31]
Ref: https://github.com/buildkite/terminal/issues/29

So I tried to use the new links, but unfortunately my plan was to use it to improve our test failure backtraces with links to GitHub. Ultimately it would work, but I'm not willing to lose the backtrace colorization I put in place:

![capture d ecran 2015-11-26 a 13 37 59](https://cloud.githubusercontent.com/assets/44640/11429229/06d81e9e-9443-11e5-860e-c4a6aead30ed.png)

Not sure what the best syntax would be to chose the link color. Ideally I could use regular ANSI color code in it:

```
echo -e '\033]1339;url=https://google.com/;content=\033[33mHello World\033[0m\a'
```

But here's what it gives me right now

![capture d ecran 2015-11-26 a 13 41 44](https://cloud.githubusercontent.com/assets/44640/11429276/c2a85706-9443-11e5-944f-e20dd947acb8.png)

@keithpitt @toolmantim @mipearson do you guys think it makes sense or am I pushing it?

**Comment by keithpitt** [comment]
I reckon we could make this happen! I think if we tweaked the URL colour to use: `color: currentColor` instead of a new URL colour, then I think it would work?

**Comment by mipearson** [comment]
hmmm. This feels more like a stylesheet change outside of terminal - remove the colour override on links within the rendered terminal section.

**Comment by keithpitt** [comment]
@byroot could you DM me a link to a build with a link in it so I can tweak da css?

**Comment by byroot** [comment]
Indeed. I just tested and all it needs is `color: inherit;` on these links.
