### ISSUE TITLE
in style.go please add Orange fg - 38, bg - 48

### ISSUE THREAD

**Issue by AyliD** [buildkite/terminal#34]
Hi,

Can you please add Orange color?
fg - 38
bg - 48

**Comment by keithpitt** [comment]
Hey @AyliD - thanks for the suggestion! I did some digging on the internet to try and find out what the offical color code for orange would be before I added it, and it looks like orange is one of the offical ANSI escape sequences?

**Comment by AyliD** [comment]
You are right, it isnt formal color, just a working color, i will change it locally in my code.
