### ISSUE TITLE
Background colours not reset and various colours not respected

### ISSUE THREAD

**Issue by josephmbeveridge** [buildkite/terminal#36]
It appears as though some of the colours aren't properly rendered, and clearing the background colour doesn't actually clear the background colour. As you can see from the expected screenshot (both using the same code), the background should end after ` P ` but it continues, and the yellow text isn't being shown.

Expected:
<img width="458" alt="screen shot 2017-02-10 at 2 20 57 pm" src="https://cloud.githubusercontent.com/assets/3857356/22840596/2d91f6a8-ef9c-11e6-93c3-6d5a666c1b68.png">

Actual:
<img width="534" alt="screen shot 2017-02-10 at 1 53 08 pm" src="https://cloud.githubusercontent.com/assets/3857356/22839676/73009a7c-ef98-11e6-80e1-0eadc9277b75.png">

**Comment by josephmbeveridge** [comment]
I don't know how to write the html for this properly, but here is the code required to show and stop showing a background partway through a line :) Should help with writing the test
```
Some plain text \e[0;30;42m yay a green background \e[0m now this has no background
```

**Comment by ticky** [comment]
Just had a dig into this - thanks for the report!

Looks like what’s happening is that Terminal is only treating the `\e[0m` as a foreground reset, not a reset of all overrides! I’ve beefed up our test case in #38.
