### ISSUE TITLE
Render images using the iTerm2 standard

### ISSUE THREAD

**Issue by keithpitt** [buildkite/terminal#8]
http://www.iterm2.com/images.html

**Comment by mipearson** [comment]
In progress: https://github.com/mipearson/terminal/tree/iTermImages

**Comment by keithpitt** [comment]
oh.
my.
stars.


:star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2: :star2:
